#!/bin/bash
# ================================================================
# Backloom v1.0 — Backup Script
# Auto-generated by install.sh — reconfigure by re-running installer
# ================================================================

# ---- Config (edit here if needed) ----
BACKUP_ROOT="/root/backloom-backups"
RCLONE_REMOTE="gdrive"
RCLONE_FOLDER="BackloomBackupsHermes"
LOCAL_KEEP=7           # keep N most recent local backups
CLOUD_KEEP_DAYS=30     # delete cloud backups older than N days

# ---- Folders to backup (add new top-level ~/folders here) ----
INCLUDE_DIRS=(
  "knowledge"
  "secondbrain"
  "projects"
  "core-stack"
  "npm"
  "pgadmin"
  "bin"
  "xauusd-bot"
  "subtrack-id"
  ".hermes"
)

# Exclude sensitive files from .hermes backup
EXCLUDE_PATTERNS="--exclude='.hermes/credentials' --exclude='.hermes/.env' --exclude='.hermes/auth.json' --exclude='.hermes/google_client_secret.json' --exclude='.hermes/google_token.json' --exclude='.hermes/state.db*' --exclude='.hermes/kanban.db' --exclude='.hermes/models_dev_cache.json' --exclude='.hermes/ollama_cloud_models_cache.json'"

# ---- Databases (format: "container|type|user|pass|dbname") ----
# type: postgres | mysql | mongo
# Add new DB containers here
DB_CONTAINERS=(
  "postgres|postgres|hermes|***|hermesdb"
  "secondbrain-db|postgres|secondbrain|sb123456|secondbrain"
)

# ---- Runtime ----
set -e
shopt -s nullglob

TIMESTAMP=$(date +%Y%m%d_%H%M%S)
WORK_DIR="${BACKUP_ROOT}/backup_${TIMESTAMP}"
mkdir -p "${WORK_DIR}/db"

echo "==> [1/5] Dumping databases..."
for entry in "${DB_CONTAINERS[@]}"; do
  IFS='|' read -r container db_type user pass dbname <<< "$entry"
  echo "    - ${container} (${db_type})"
  case "$db_type" in
    postgres)
      docker exec -e PGPASSWORD="$pass" "$container" \
        pg_dumpall -U "$user" > "${WORK_DIR}/db/${container}.sql"
      ;;
    mysql)
      docker exec -e MYSQL_PWD="$pass" "$container" \
        mysqldump -u "$user" --all-databases > "${WORK_DIR}/db/${container}.sql"
      ;;
    mongo)
      docker exec "$container" mongodump --archive > "${WORK_DIR}/db/${container}.archive"
      ;;
  esac
done

echo "==> [2/5] Archiving agent files..."
cd ~
tar -czf "${WORK_DIR}/agent-files.tar.gz" \
  --exclude='node_modules' \
  --exclude='__pycache__' \
  --exclude='venv' \
  --exclude='.venv' \
  --exclude='dist' \
  --exclude='build' \
  --exclude='.next' \
  ${EXCLUDE_PATTERNS} \
  "${INCLUDE_DIRS[@]}" \
  todo-*.md todo-carryover.sh todo-template.md *.log 2>/dev/null || true

docker ps -a --format '{{.Names}}\t{{.Image}}\t{{.Status}}' > "${WORK_DIR}/containers.txt"

echo "==> [3/5] Packaging..."
FINAL_FILE="${BACKUP_ROOT}/backloom-${TIMESTAMP}.tar.gz"
tar -czf "$FINAL_FILE" -C "$BACKUP_ROOT" "backup_${TIMESTAMP}"
rm -rf "$WORK_DIR"

echo "==> [4/5] Uploading to cloud..."
if [[ -n "$RCLONE_REMOTE" ]]; then
  rclone copy "$FINAL_FILE" "${RCLONE_REMOTE}:${RCLONE_FOLDER}/"
  rclone delete "${RCLONE_REMOTE}:${RCLONE_FOLDER}/" \
    --min-age "${CLOUD_KEEP_DAYS}d" 2>/dev/null || true
  echo "    Uploaded: ${RCLONE_REMOTE}:${RCLONE_FOLDER}/$(basename "$FINAL_FILE")"
else
  echo "    [SKIP] No cloud remote configured"
fi

echo "==> [5/5] Cleanup local (keep ${LOCAL_KEEP})..."
ls -t "${BACKUP_ROOT}"/backloom-*.tar.gz 2>/dev/null \
  | tail -n +$((LOCAL_KEEP + 1)) | xargs -r rm -f

echo ""
echo "Done ✓  $(du -sh "$FINAL_FILE" | cut -f1)  →  $FINAL_FILE"
